import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { Loader2 } from "lucide-react";

const formSchema = z.object({
  tipo_solicitud: z.enum(["peticion", "queja", "reclamo"], {
    required_error: "Debes seleccionar un tipo de solicitud",
  }),
  nombre_completo: z.string()
    .min(3, "El nombre debe tener al menos 3 caracteres")
    .max(100, "El nombre no puede exceder 100 caracteres")
    .trim(),
  tipo_documento: z.enum(["CC", "CE", "NIT", "Pasaporte", "TI"], {
    required_error: "Debes seleccionar un tipo de documento",
  }),
  documento_identidad: z.string()
    .min(5, "El documento debe tener al menos 5 caracteres")
    .max(20, "El documento no puede exceder 20 caracteres")
    .trim(),
  direccion: z.string()
    .min(10, "La dirección debe tener al menos 10 caracteres")
    .max(200, "La dirección no puede exceder 200 caracteres")
    .trim(),
  telefono: z.string()
    .min(7, "El teléfono debe tener al menos 7 dígitos")
    .max(15, "El teléfono no puede exceder 15 dígitos")
    .trim(),
  email: z.string()
    .email("Correo electrónico inválido")
    .max(255, "El correo no puede exceder 255 caracteres")
    .trim(),
  descripcion: z.string()
    .min(20, "La descripción debe tener al menos 20 caracteres")
    .max(2000, "La descripción no puede exceder 2000 caracteres")
    .trim(),
});

type FormValues = z.infer<typeof formSchema>;

const PQRForm = () => {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [radicadoNumber, setRadicadoNumber] = useState<string | null>(null);

  const form = useForm<FormValues>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      tipo_solicitud: undefined,
      nombre_completo: "",
      tipo_documento: undefined,
      documento_identidad: "",
      direccion: "",
      telefono: "",
      email: "",
      descripcion: "",
    },
  });

  const onSubmit = async (values: FormValues) => {
    setIsSubmitting(true);
    setRadicadoNumber(null);

    try {
      const { data, error } = await supabase
        .from("pqrs")
        .insert({
          tipo_solicitud: values.tipo_solicitud,
          nombre_completo: values.nombre_completo,
          tipo_documento: values.tipo_documento,
          documento_identidad: values.documento_identidad,
          direccion: values.direccion,
          telefono: values.telefono,
          email: values.email,
          descripcion: values.descripcion,
          radicado_number: "", // Will be auto-generated by trigger
        })
        .select("radicado_number")
        .single();

      if (error) throw error;

      setRadicadoNumber(data.radicado_number);
      
      toast({
        title: "PQR Radicada Exitosamente",
        description: `Tu número de radicado es: ${data.radicado_number}. Guárdalo para consultar el estado.`,
      });

      form.reset();
    } catch (error: any) {
      toast({
        variant: "destructive",
        title: "Error",
        description: error.message || "Ocurrió un error al radicar tu PQR. Por favor intenta nuevamente.",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Radicar Nueva PQR</CardTitle>
        <CardDescription>
          Completa el formulario con tus datos y describe tu solicitud. Recibirás un número de radicado para hacer seguimiento.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {radicadoNumber && (
          <div className="mb-6 p-4 bg-primary/10 border border-primary/20 rounded-lg">
            <p className="font-semibold text-lg mb-2">¡PQR Radicada Exitosamente!</p>
            <p className="text-muted-foreground">Tu número de radicado es:</p>
            <p className="text-2xl font-bold text-primary mt-2">{radicadoNumber}</p>
            <p className="text-sm text-muted-foreground mt-2">
              Guarda este número para consultar el estado de tu solicitud.
            </p>
          </div>
        )}

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            <FormField
              control={form.control}
              name="tipo_solicitud"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Tipo de Solicitud *</FormLabel>
                  <Select onValueChange={field.onChange} value={field.value}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Selecciona el tipo" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      <SelectItem value="peticion">Petición</SelectItem>
                      <SelectItem value="queja">Queja</SelectItem>
                      <SelectItem value="reclamo">Reclamo</SelectItem>
                    </SelectContent>
                  </Select>
                  <FormMessage />
                </FormItem>
              )}
            />

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="nombre_completo"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Nombre Completo *</FormLabel>
                    <FormControl>
                      <Input placeholder="Ej: Juan Pérez García" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="email"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Correo Electrónico *</FormLabel>
                    <FormControl>
                      <Input type="email" placeholder="correo@ejemplo.com" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="tipo_documento"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Tipo de Documento *</FormLabel>
                    <Select onValueChange={field.onChange} value={field.value}>
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Selecciona" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        <SelectItem value="CC">Cédula de Ciudadanía</SelectItem>
                        <SelectItem value="CE">Cédula de Extranjería</SelectItem>
                        <SelectItem value="NIT">NIT</SelectItem>
                        <SelectItem value="Pasaporte">Pasaporte</SelectItem>
                        <SelectItem value="TI">Tarjeta de Identidad</SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="documento_identidad"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Número de Documento *</FormLabel>
                    <FormControl>
                      <Input placeholder="Ej: 1234567890" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <FormField
                control={form.control}
                name="telefono"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Teléfono *</FormLabel>
                    <FormControl>
                      <Input placeholder="Ej: 3001234567" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="direccion"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Dirección *</FormLabel>
                    <FormControl>
                      <Input placeholder="Ej: Calle 123 #45-67" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <FormField
              control={form.control}
              name="descripcion"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Descripción de tu Solicitud *</FormLabel>
                  <FormControl>
                    <Textarea
                      placeholder="Describe detalladamente tu petición, queja o reclamo..."
                      className="min-h-[150px]"
                      {...field}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <Button type="submit" className="w-full" disabled={isSubmitting}>
              {isSubmitting ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Radicando...
                </>
              ) : (
                "Radicar PQR"
              )}
            </Button>
          </form>
        </Form>
      </CardContent>
    </Card>
  );
};

export default PQRForm;
